In [27]:
import numpy as np
h=np.arange(5)
h


array([0, 1, 2, 3, 4])

In [28]:
h= np.arange(9).reshape(3,3)
h

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
print(h.ndim)
print(h.shape)
print(h.size)
print(h.dtype)
print(h.itemsize)
print(type(h))

m=np.eye (5, dtype=np.int32)
print(m)
print(m.dtype)

2
(3, 3)
9
int32
4
<class 'numpy.ndarray'>
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
int32


In [30]:
h= np.arange(9).reshape(3,3)
print(h*2)


[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
