# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [134]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [135]:
#can get the range by multipe the o/p (b-a)+a
c=np.random.random_sample((10,10))
10*c

array([[ 1.01724239,  7.81242939,  3.24664349,  9.10251807,  5.20290015,
         2.42632242,  1.31212582,  9.09407917,  9.01926327,  7.4731452 ],
       [ 3.55321994,  8.29095768,  7.79203658,  9.31545912,  3.60474611,
         0.14943504,  8.25499255,  8.52932437,  6.76040178,  2.13277504],
       [ 9.56312374,  3.0506981 ,  2.43101329,  1.88307301,  2.97104289,
         5.94600966,  2.84788007,  7.39544042,  7.53540304,  2.00123249],
       [ 7.23923617,  7.60243882,  1.98692243,  4.87078211,  8.96551934,
         3.56675584,  7.81112036,  5.86068192,  0.263455  ,  1.68306203],
       [ 3.70076833,  3.17519553,  8.79316359,  6.56344948,  2.95223142,
         9.93304362,  7.015817  ,  9.09385748,  7.30234067,  0.59433898],
       [ 1.62185552,  3.77105313,  7.1615152 ,  2.99259391,  7.73583962,
         0.09076631,  5.00826548,  3.87492771,  9.59089475,  3.96680177],
       [ 8.92397567,  1.71459471,  6.63638166,  6.08268695,  3.39879813,
         0.16257567,  8.37889409,  2.9938373 

## Q2

Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [157]:
a=np.arange(15).reshape(3,5)
b=np.ones((3,5) ,dtype=np.int32)
c=a+b
d=c.transpose()
print (d)
f=d[np.logical_and(d>=2, d<=4)

SyntaxError: unexpected EOF while parsing (<ipython-input-157-5c5ff6897617>, line 6)

++++++++++++++## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [137]:
m=np.ones((4,5) , dtype=np.int32 )
m[1:3,1:4]=0
m

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [158]:
rad = np.arange(7)*(np.pi/6)/2
print(np.degrees(rad))
print()
a=np.sin(rad)
print(a)
print()
b=np.cos(rad)
print(b)
c=np.tan(rad)
print(c)


[  0.  15.  30.  45.  60.  75.  90.]

[ 0.          0.25881905  0.5         0.70710678  0.8660254   0.96592583
  1.        ]

[  1.00000000e+00   9.65925826e-01   8.66025404e-01   7.07106781e-01
   5.00000000e-01   2.58819045e-01   6.12323400e-17]
[  0.00000000e+00   2.67949192e-01   5.77350269e-01   1.00000000e+00
   1.73205081e+00   3.73205081e+00   1.63312394e+16]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [139]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
np.diff(x)
x[1:] - x[:-1]

array([-2,  3,  3,  3, -4,  6,  2, -9])

## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:
$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`